require('nvim-web-devicons').setup({
  override_by_extension = {
    ["7z"] = { icon = "", name = "7z" },
    ["DS_Store"] = { icon = "", color = "#c1f12e", name = "DsStore" },
    ["aac"] = { icon = "", name = "Aac" },
    ["ace"] = { icon = "", name = "Ace" },
    ["ai"] = { icon = "", color = "#cbcb41", name = "Ai" },
    ["alz"] = { icon = "", name = "Alz" },
    ["arc"] = { icon = "", name = "Arc" },
    ["arj"] = { icon = "", name = "Arj" },
    ["asf"] = { icon = "", name = "Asf" },
    ["au"] = { icon = "", name = "Au" },
    ["avi"] = { icon = "", name = "Avi" },
    ["awk"] = { icon = "", color = "#89e051", name = "Awk" },
    ["bash"] = { icon = "", color = "#89e051", name = "Bash" },
    ["bashprofile"] = { icon = "", color = "#89e051", name = "Bashprofile" },
    ["bashrc"] = { icon = "", color = "#89e051", name = "Bashrc" },
    ["bat"] = { icon = "", color = "#c1f12e", name = "Bat" },
    ["bib"] = { icon = "󱉟", color = "#cbcb41", name = "Bib" },
    ["bmp"] = { icon = "", name = "Bmp" },
    ["bz"] = { icon = "", name = "Bz" },
    ["bz2"] = { icon = "", name = "Bz2" },
    ["c"] = { icon = "", color = "#599eff", name = "C" },
    ["c++"] = { icon = "", color = "#599eff", name = "C" },
    ["cab"] = { icon = "", name = "Cab" },
    ["cc"] = { icon = "", color = "#519aba", name = "Cc" },
    ["cgm"] = { icon = "", name = "Cgm" },
    ["clj"] = { icon = "", color = "#8dc149", name = "Clj" },
    ["cljc"] = { icon = "", color = "#8dc149", name = "Cljc" },
    ["cljs"] = { icon = "", color = "#519aba", name = "Cljs" },
    ["coffee"] = { icon = "", color = "#cbcb41", name = "Coffee" },
    ["conf"] = { icon = "", color = "#6d8086", name = "Conf" },
    ["cp"] = { icon = "", color = "#519aba", name = "Cp" },
    ["cpio"] = { icon = "", name = "Cpio" },
    ["cpp"] = { icon = "", color = "#519aba", name = "Cpp" },
    ["cs"] = { icon = "󰌛", color = "#596706", name = "Cs" },
    ["csh"] = { icon = "", color = "#89e051", name = "Csh" },
    ["css"] = { icon = "", color = "#563d7c", name = "Css" },
    ["csv"] = { icon = "󰈙", color = "#89e051", name = "Csv" },
    ["cxx"] = { icon = "", color = "#519aba", name = "Cxx" },
    ["d"] = { icon = "", color = "#427819", name = "D" },
    ["dart"] = { icon = "", color = "#03589c", name = "Dart" },
    ["db"] = { icon = "", color = "#dad8d8", name = "Db" },
    ["deb"] = { icon = "", name = "Deb" },
    ["diff"] = { icon = "", color = "#41535b", name = "Diff" },
    ["dl"] = { icon = "", name = "Dl" },
    ["doc"] = { icon = "󰈬", color = "#185abd", name = "Doc" },
    ["docx"] = { icon = "󰈬", color = "#185abd", name = "Docx" },
    ["ds_store"] = { icon = "", color = "#4d5a5e", name = "DsStore" },
    ["dump"] = { icon = "", color = "#dad8d8", name = "Dump" },
    ["dwm"] = { icon = "", name = "Dwm" },
    ["dz"] = { icon = "", name = "Dz" },
    ["ear"] = { icon = "", name = "Ear" },
    ["edn"] = { icon = "", color = "#519aba", name = "Edn" },
    ["eex"] = { icon = "", color = "#a074c4", name = "Eex" },
    ["ejs"] = { icon = "", color = "#cbcb41", name = "Ejs" },
    ["elm"] = { icon = "", color = "#519aba", name = "Elm" },
    ["emf"] = { icon = "", name = "Emf" },
    ["erl"] = { icon = "", color = "#b83998", name = "Erl" },
    ["esd"] = { icon = "", name = "Esd" },
    ["ex"] = { icon = "", color = "#a074c4", name = "Ex" },
    ["exs"] = { icon = "", color = "#a074c4", name = "Exs" },
    ["fish"] = { icon = "", color = "#89e051", name = "Fish" },
    ["flac"] = { icon = "", name = "Flac" },
    ["flc"] = { icon = "", name = "Flc" },
    ["fli"] = { icon = "", name = "Fli" },
    ["flv"] = { icon = "", name = "Flv" },
    ["fs"] = { icon = "", color = "#519aba", name = "Fs" },
    ["fsi"] = { icon = "", color = "#519aba", name = "Fsi" },
    ["fsscript"] = { icon = "", color = "#519aba", name = "Fsscript" },
    ["fsx"] = { icon = "", color = "#519aba", name = "Fsx" },
    ["gemspec"] = { icon = "", color = "#701516", name = "Gemspec" },
    ["gif"] = { icon = "", name = "Gif" },
    ["gitattributes"] = { icon = "", color = "#41535b", name = "Gitattributes" },
    ["gitconfig"] = { icon = "", color = "#41535b", name = "Gitconfig" },
    ["gitignore"] = { icon = "", color = "#41535b", name = "Gitignore" },
    ["gitlab-ci.yml"] = { icon = "", color = "#e24329", name = "GitlabCiYml" },
    ["gl"] = { icon = "", name = "Gl" },
    ["go"] = { icon = "", color = "#519aba", name = "Go" },
    ["gvimrc"] = { icon = "", color = "#019833", name = "Gvimrc" },
    ["gz"] = { icon = "", name = "Gz" },
    ["h"] = { icon = "", color = "#a074c4", name = "H" },
    ["haml"] = { icon = "", color = "#eaeae1", name = "Haml" },
    ["hbs"] = { icon = "", color = "#f0772b", name = "Hbs" },
    ["heex"] = { icon = "", color = "#a074c4", name = "Heex" },
    ["hh"] = { icon = "", color = "#a074c4", name = "Hh" },
    ["hpp"] = { icon = "", color = "#a074c4", name = "Hpp" },
    ["hrl"] = { icon = "", color = "#b83998", name = "Hrl" },
    ["hs"] = { icon = "", color = "#a074c4", name = "Hs" },
    ["htm"] = { icon = "", color = "#e34c26", name = "Htm" },
    ["html"] = { icon = "", color = "#e34c26", name = "Html" },
    ["hxx"] = { icon = "", color = "#a074c4", name = "Hxx" },
    ["ico"] = { icon = "", color = "#cbcb41", name = "Ico" },
    ["ini"] = { icon = "", color = "#6d8086", name = "Ini" },
    ["jar"] = { icon = "", name = "Jar" },
    ["java"] = { icon = "", color = "#cc3e44", name = "Java" },
    ["jl"] = { icon = "", color = "#a270ba", name = "Jl" },
    ["jpeg"] = { icon = "", name = "Jpeg" },
    ["jpg"] = { icon = "", name = "Jpg" },
    ["js"] = { icon = "", color = "#cbcb41", name = "Js" },
    ["json"] = { icon = "", color = "#959da5", name = "Json" },
    ["jsx"] = { icon = "", color = "#519aba", name = "Jsx" },
    ["ksh"] = { icon = "", color = "#89e051", name = "Ksh" },
    ["leex"] = { icon = "", color = "#a074c4", name = "Leex" },
    ["less"] = { icon = "", color = "#563d7c", name = "Less" },
    ["lha"] = { icon = "", name = "Lha" },
    ["lhs"] = { icon = "", color = "#a074c4", name = "Lhs" },
    ["lrz"] = { icon = "", name = "Lrz" },
    ["lua"] = { icon = "", color = "#51a0cf", name = "Lua" },
    ["lz"] = { icon = "", name = "Lz" },
    ["lz4"] = { icon = "", name = "Lz4" },
    ["lzh"] = { icon = "", name = "Lzh" },
    ["lzma"] = { icon = "", name = "Lzma" },
    ["lzo"] = { icon = "", name = "Lzo" },
    ["m2v"] = { icon = "", name = "M2v" },
    ["m4a"] = { icon = "", name = "M4a" },
    ["m4v"] = { icon = "", name = "M4v" },
    ["markdown"] = { icon = "", color = "#519aba", name = "Markdown" },
    ["md"] = { icon = "", color = "#519aba", name = "Md" },
    ["mdx"] = { icon = "", color = "#519aba", name = "Mdx" },
    ["mid"] = { icon = "", name = "Mid" },
    ["midi"] = { icon = "", name = "Midi" },
    ["mjpeg"] = { icon = "", name = "Mjpeg" },
    ["mjpg"] = { icon = "", name = "Mjpg" },
    ["mjs"] = { icon = "", color = "#f1e05a", name = "Mjs" },
    ["mk"] = { icon = "", color = "#6d8086", name = "Mk" },
    ["mka"] = { icon = "", name = "Mka" },
    ["mkv"] = { icon = "", name = "Mkv" },
    ["ml"] = { icon = "λ", color = "#e37933", name = "Ml" },
    ["mli"] = { icon = "λ", color = "#e37933", name = "Mli" },
    ["mng"] = { icon = "", name = "Mng" },
    ["mov"] = { icon = "", name = "Mov" },
    ["mp3"] = { icon = "", name = "Mp3" },
    ["mp4"] = { icon = "", name = "Mp4" },
    ["mp4v"] = { icon = "", name = "Mp4v" },
    ["mpc"] = { icon = "", name = "Mpc" },
    ["mpeg"] = { icon = "", name = "Mpeg" },
    ["mpg"] = { icon = "", name = "Mpg" },
    ["mustache"] = { icon = "", color = "#e37933", name = "Mustache" },
    ["nix"] = { icon = "", color = "#7ebae4", name = "Nix" },
    ["nuv"] = { icon = "", name = "Nuv" },
    ["oga"] = { icon = "", name = "Oga" },
    ["ogg"] = { icon = "", name = "Ogg" },
    ["ogm"] = { icon = "", name = "Ogm" },
    ["ogv"] = { icon = "", name = "Ogv" },
    ["ogx"] = { icon = "", name = "Ogx" },
    ["opus"] = { icon = "", name = "Opus" },
    ["pbm"] = { icon = "", name = "Pbm" },
    ["pcx"] = { icon = "", name = "Pcx" },
    ["pdf"] = { icon = "", color = "#b30b00", name = "Pdf" },
    ["pem"] = { icon = "", color = "#cd9b3e", name = "Pem" },
    ["pgm"] = { icon = "", name = "Pgm" },
    ["php"] = { icon = "", color = "#a074c4", name = "Php" },
    ["pl"] = { icon = "", color = "#519aba", name = "Pl" },
    ["pm"] = { icon = "", color = "#519aba", name = "Pm" },
    ["png"] = { icon = "", name = "Png" },
    ["pp"] = { icon = "", color = "#ffa61a", name = "Pp" },
    ["ppm"] = { icon = "", name = "Ppm" },
    ["ps1"] = { icon = "", color = "#89e051", name = "Ps1" },
    ["psb"] = { icon = "", color = "#519aba", name = "Psb" },
    ["psd"] = { icon = "", color = "#519aba", name = "Psd" },
    ["py"] = { icon = "", color = "#519aba", name = "Py" },
    ["pyc"] = { icon = "", color = "#519aba", name = "Pyc" },
    ["pyd"] = { icon = "", color = "#519aba", name = "Pyd" },
    ["pyo"] = { icon = "", color = "#519aba", name = "Pyo" },
    ["qt"] = { icon = "", name = "Qt" },
    ["r"] = { icon = "󰟔", color = "#358a5b", name = "R" },
    ["ra"] = { icon = "", name = "Ra" },
    ["rake"] = { icon = "", color = "#701516", name = "Rake" },
    ["rar"] = { icon = "", name = "Rar" },
    ["rb"] = { icon = "", color = "#701516", name = "Rb" },
    ["rlib"] = { icon = "", color = "#dea584", name = "Rlib" },
    ["rm"] = { icon = "", name = "Rm" },
    ["rmd"] = { icon = "", color = "#519aba", name = "Rmd" },
    ["rmvb"] = { icon = "", name = "Rmvb" },
    ["rpm"] = { icon = "", name = "Rpm" },
    ["rproj"] = { icon = "󰗆", color = "#358a5b", name = "Rproj" },
    ["rs"] = { icon = "", color = "#dea584", name = "Rs" },
    ["rss"] = { icon = "", color = "#fb9d3b", name = "Rss" },
    ["rz"] = { icon = "", name = "Rz" },
    ["sar"] = { icon = "", name = "Sar" },
    ["sass"] = { icon = "", color = "#f55385", name = "Sass" },
    ["scala"] = { icon = "", color = "#cc3e44", name = "Scala" },
    ["scss"] = { icon = "", color = "#f55385", name = "Scss" },
    ["sh"] = { icon = "", color = "#89e051", name = "Sh" },
    ["slim"] = { icon = "", color = "#e34c26", name = "Slim" },
    ["sln"] = { icon = "", color = "#854cc7", name = "Sln" },
    ["sol"] = { icon = "󰡪", color = "#519aba", name = "Sol" },
    ["spx"] = { icon = "", name = "Spx" },
    ["sql"] = { icon = "", color = "#dad8d8", name = "Sql" },
    ["styl"] = { icon = "", color = "#8dc149", name = "Styl" },
    ["suo"] = { icon = "", color = "#854cc7", name = "Suo" },
    ["svg"] = { icon = "", name = "Svg" },
    ["svgz"] = { icon = "", name = "Svgz" },
    ["swift"] = { icon = "", color = "#e37933", name = "Swift" },
    ["swm"] = { icon = "", name = "Swm" },
    ["t"] = { icon = "", color = "#519aba", name = "T" },
    ["t7z"] = { icon = "", name = "T7z" },
    ["tar"] = { icon = "", name = "Tar" },
    ["taz"] = { icon = "", name = "Taz" },
    ["tbz"] = { icon = "", name = "Tbz" },
    ["tbz2"] = { icon = "", name = "Tbz2" },
    ["tex"] = { icon = "", color = "#3d6117", name = "Tex" },
    ["tga"] = { icon = "", name = "Tga" },
    ["tgz"] = { icon = "", name = "Tgz" },
    ["tif"] = { icon = "", name = "Tif" },
    ["tiff"] = { icon = "", name = "Tiff" },
    ["tlz"] = { icon = "", name = "Tlz" },
    ["toml"] = { icon = "", color = "#6d8086", name = "Toml" },
    ["ts"] = { icon = "", color = "#519aba", name = "Ts" },
    ["tsx"] = { icon = "", color = "#519aba", name = "Tsx" },
    ["twig"] = { icon = "", color = "#8dc149", name = "Twig" },
    ["txt"] = { icon = "󰈙", color = "#89e051", name = "Txt" },
    ["txz"] = { icon = "", name = "Txz" },
    ["tz"] = { icon = "", name = "Tz" },
    ["tzo"] = { icon = "", name = "Tzo" },
    ["tzst"] = { icon = "", name = "Tzst" },
    ["vim"] = { icon = "", color = "#019833", name = "Vim" },
    ["vimrc"] = { icon = "", color = "#019833", name = "Vimrc" },
    ["vob"] = { icon = "", name = "Vob" },
    ["vue"] = { icon = "", color = "#8dc149", name = "Vue" },
    ["war"] = { icon = "", name = "War" },
    ["wav"] = { icon = "", name = "Wav" },
    ["webm"] = { icon = "", name = "Webm" },
    ["webmanifest"] = { icon = "", color = "#f1e05a", name = "Webmanifest" },
    ["webp"] = { icon = "", color = "#a074c4", name = "Webp" },
    ["wim"] = { icon = "", name = "Wim" },
    ["wmv"] = { icon = "", name = "Wmv" },
    ["xbm"] = { icon = "", name = "Xbm" },
    ["xcf"] = { icon = "", name = "Xcf" },
    ["xcplayground"] = { icon = "", color = "#e37933", name = "Xcplayground" },
    ["xls"] = { icon = "󰈛", color = "#207245", name = "Xls" },
    ["xlsx"] = { icon = "󰈛", color = "#207245", name = "Xlsx" },
    ["xpm"] = { icon = "", name = "Xpm" },
    ["xspf"] = { icon = "", name = "Xspf" },
    ["xul"] = { icon = "", color = "#e37933", name = "Xul" },
    ["xwd"] = { icon = "", name = "Xwd" },
    ["xz"] = { icon = "", name = "Xz" },
    ["yaml"] = { icon = "", color = "#959da5", name = "Yaml" },
    ["yml"] = { icon = "", color = "#959da5", name = "Yml" },
    ["yuv"] = { icon = "", name = "Yuv" },
    ["z"] = { icon = "", name = "Z" },
    ["zip"] = { icon = "", name = "Zip" },
    ["zoo"] = { icon = "", name = "Zoo" },
    ["zprofile"] = { icon = "", color = "#89e051", name = "Zprofile" },
    ["zsh"] = { icon = "", color = "#89e051", name = "Zsh" },
    ["zshenv"] = { icon = "", color = "#89e051", name = "Zshenv" },
    ["zshrc"] = { icon = "", color = "#89e051", name = "Zshrc" },
    ["zst"] = { icon = "", name = "Zst" },
  },
  override_by_filename = {
    ["'*.f#'"] = { icon = "", color = "#519aba", name = "F" },
    ["CMakeLists.txt"] = { icon = "", color = "#6d8086", name = "CmakelistsTxt" },
    ["Docker-compose.yaml"] = { icon = "", color = "#519aba", name = "DockerComposeYaml" },
    ["Docker-compose.yml"] = { icon = "", color = "#519aba", name = "DockerComposeYml" },
    ["Gruntfile.coffee"] = { icon = "", color = "#e37933", name = "GruntfileCoffee" },
    ["Gruntfile.js"] = { icon = "", color = "#e37933", name = "GruntfileJs" },
    ["Gruntfile.ls"] = { icon = "", color = "#e37933", name = "GruntfileLs" },
    ["Gulpfile.coffee"] = { icon = "", color = "#cc3e44", name = "GulpfileCoffee" },
    ["Gulpfile.js"] = { icon = "", color = "#cc3e44", name = "GulpfileJs" },
    ["Gulpfile.ls"] = { icon = "", color = "#cc3e44", name = "GulpfileLs" },
    ["React.jsx"] = { icon = "", color = "#519aba", name = "ReactJsx" },
    ["angular.min.js"] = { icon = "", color = "#e23237", name = "AngularMinJs" },
    ["backbone.min.js"] = { icon = "", color = "#0071b5", name = "BackboneMinJs" },
    ["cmakelists.txt"] = { icon = "", color = "#6d8086", name = "CmakelistsTxt" },
    ["compose.yaml"] = { icon = "", color = "#519aba", name = "ComposeYaml" },
    ["compose.yml"] = { icon = "", color = "#519aba", name = "ComposeYml" },
    ["config.ru"] = { icon = "", color = "#701516", name = "ConfigRu" },
    ["docker-compose.yaml"] = { icon = "", color = "#519aba", name = "DockerComposeYaml" },
    ["docker-compose.yml"] = { icon = "", color = "#519aba", name = "DockerComposeYml" },
    ["favicon.ico"] = { icon = "", color = "#cbcb41", name = "FaviconIco" },
    ["gruntfile.coffee"] = { icon = "", color = "#e37933", name = "GruntfileCoffee" },
    ["gruntfile.js"] = { icon = "", color = "#e37933", name = "GruntfileJs" },
    ["gruntfile.ls"] = { icon = "", color = "#e37933", name = "GruntfileLs" },
    ["gulpfile.coffee"] = { icon = "", color = "#cc3e44", name = "GulpfileCoffee" },
    ["gulpfile.js"] = { icon = "", color = "#cc3e44", name = "GulpfileJs" },
    ["gulpfile.ls"] = { icon = "", color = "#cc3e44", name = "GulpfileLs" },
    ["jquery.min.js"] = { icon = "", color = "#e375bb", name = "JqueryMinJs" },
    ["materialize.min.css"] = { icon = "", color = "#ee6e73", name = "MaterializeMinCss" },
    ["materialize.min.js"] = { icon = "", color = "#ee6e73", name = "MaterializeMinJs" },
    ["mix.lock"] = { icon = "", color = "#a074c4", name = "MixLock" },
    ["mootools.min.js"] = { icon = "", color = "#ececec", name = "MootoolsMinJs" },
    ["react.jsx"] = { icon = "", color = "#519aba", name = "ReactJsx" },
    ["require.min.js"] = { icon = "", color = "#f44a41", name = "RequireMinJs" },
    ["robots.txt"] = { icon = "󰚩", color = "#6d8086", name = "RobotsTxt" },
  },
})
