#!/bin/sh
while read file
do
    case "$1" in
        "b")
            setbg "$file" & ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
            convert -rotate -90 "$file" "$file" ;;
        "f")
            convert -flop "$file" "$file" ;;
        "y")
            printf "$file" | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" & ;;
        "g")
            ifinstalled gimp && setsid -f gimp "$file" ;;
        "i")
            notify-send "File information" "$(mediainfo "$file" | tr -s ' ')" ;;
    esac
done