#!/bin/sh

draw() {
  ~/.config/lf/drawer "$@"
  exit 1
}

hasher() {
  printf '%s/.cache/lf/%s' "$HOME" \
    "$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
}

cache() {
  if [ -f "$1" ]; then
    draw "$@"
  fi
}

file="$1"
shift

if [ -n "$FIFO_UEBERZUG" ]; then
    case "$(file --dereference --brief --mime-type -- "$file")" in
        image/*)
          orientation="$(identify -format '%[EXIF:Orientation]\n' -- "$file")"
          if [ -n "$orientation" ] && [ "$orientation" != 1 ]; then
            cache="$(hasher "$file").jpg"
            cache "$cache" "$@"
            convert -- "$file" -auto-orient "$cache"
            draw "$cache" "$@"
          else
            draw "$file" "$@"
          fi
          ;;
        text/html) lynx -width="$4" -display_charset=utf-8 -dump "$file"  ;;
        text/troff) man ./ "$file" | col -b ;;
        text/* | */xml | */json | */x-subrip) bat --paging=never --terminal-width "$(($4-10))" --wrap character --color=always "$file" ;;
        application/zip) atool --list -- "$file" ;;
        application/gzip) tar tzf "$file" ;;
        application/x-pie-executable | application/x-object) echo "Binary cannot be previewed." ;;
        audio/* | application/octet-stream) mediainfo "$file" || exit 1;;
        video/*)
          cache="$(hasher "$file").jpg"
          cache "$cache" "$@"
          ffmpegthumbnailer -i "$file" -o "$cache" -s 0
          draw "$cache" "$@"
          ;;
        */pdf)
          cache="$(hasher "$file")"
          cache "$cache.jpg" "$@"
          pdftoppm -r 450 -jpeg -f 1 -singlefile "$file" "$cache"
          draw "$cache.jpg" "$@"
          ;;
        *opendocument*) odt2txt "$file" ;;
        application/pgp-encrypted) gpg -d -- "$file" ;;
    esac
fi

file -Lb -- "$1" | fold -s -w "$width"
exit 0
