#!/bin/sh

draw() {
  path="$(readlink -f -- "$1" | sed 's/\\/\\\\/g;s/"/\\"/g')"
  printf '{"action": "add", "identifier": "preview", "x": %d, "y": %d, "width": %d, "height": %d, "scaler": "contain", "scaling_position_x": 0.5, "scaling_position_y": 0.5, "path": "%s"}\n' \
    "$x" "$y" "$width" "$height" "$path" >"$FIFO_UEBERZUG"
  exit 1
}

hasher() {
  printf '%s/.cache/lf/%s' "$HOME" \
    "$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
}

cache() {
  if [ -f "$1" ]; then
    draw "$@"
  fi
}

file="$1"
width="$2"
height="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type -- "$file")" in
  image/*)
    if [ -p "$FIFO_UEBERZUG" ]; then
      orientation="$(magick identify -format '%[orientation]\n' -- "$file[0]")"
      if [ -n "$orientation" ] &&
        [ "$orientation" != Undefined ] &&
        [ "$orientation" != TopLeft ]; then
        cache="$(hasher "$file").jpg"
        cache "$cache" "$@"
        magick -- "$file[0]" -auto-orient "$cache"
        draw "$cache"
      else
        draw "$file"
      fi
    fi
    ;;
  text/html) lynx -width="$width" -display_charset=utf-8 -dump "$file" ;;
  text/troff) man ./ "$file" | col -b ;;
  text/* | */xml | */json | */x-subrip | */javascript) bat --paging=never --terminal-width "$width" --wrap character --color=always "$file" ;;
  */*wordprocessingml.document) docx2txt "$file" - | fold -s -w "$width" ;;
  */*spreadsheetml.sheet) xlsx2csv "$file" ;;
  application/zip) atool --list -- "$file" ;;
  application/gzip) tar tzf "$file" ;;
  audio/* | application/octet-stream) mediainfo "$file" || exit 1 ;;
  video/*)
    if [ -p "$FIFO_UEBERZUG" ]; then
      cache="$(hasher "$file").jpg"
      cache "$cache" "$@"
      ffmpegthumbnailer -i "$file" -o "$cache" -s 0
      draw "$cache"
    fi
    ;;
  */pdf)
    if [ -p "$FIFO_UEBERZUG" ]; then
      cache="$(hasher "$file")"
      cache "$cache.jpg" "$@"
      pdftoppm -r 450 -jpeg -f 1 -singlefile "$file" "$cache"
      draw "$cache.jpg"
    fi
    ;;
  *opendocument*) odt2txt "$file" ;;
  application/pgp-encrypted) gpg -d -- "$file" ;;
esac

file -Lb -- "$file" | fold -s -w "$width"
exit 0
