#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv updatedb; do
    alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
    ls="ls --color=auto -hN --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    g="git" \
    se="sudoedit" \
    sdn="loginctl poweroff" \
    copy="xclip -selection clipboard" \
    mp="pdfunite" \
    p="sudo pacman" \
    z="zathura" \
    e="$EDITOR" \
    v="$EDITOR"

# Shorten some common curl commands.
alias \
    we="curl -s 'wttr.in/?%F' | less -S" \
    wee="curl -s 'v2.wttr.in/?%F' | less -S" \
    temp="curl -s 'wttr.in/$LOCATION?format='%c%t+\(%f\)''" \
    sunset="curl -s 'wttr.in/$LOCATION?format=%s'" \
    iplocate="curl -s ifconfig.co"

alias \
    lf="lfub" \
    magit="nvim -c MagitOnly"
