#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &             # set the background with the `setbg` script
remaps &            # run the `remaps` script, switching caps/esc and more
mpd &               # music player daemon
dunst &             # enables desktop notifications
unclutter &         # hide mouse when idle
xbanish -i mod4 &   # hide mouse when typing
numlockx &          # remember numlock
redshift &          # provides redshift in the screen in the evening
xcompmgr &          # for transparency